{
  "formatVersion": "1.1",
  "component": {
    "group": "org.amnezia.awg",
    "module": "awg-tunnel",
    "version": "1.0.20260624",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "awg-tunnel-1.0.20260624.aar",
          "url": "awg-tunnel-1.0.20260624.aar",
          "size": 6027587,
          "sha512": "8aeea53ecacbc7eeac915295da058402e51ffd3ac95e22735855ffa7d092aabfba9dbac73116ed30b0a4bba9702c98d931657067eb9ce3a8da9422c50d00b93a",
          "sha256": "4906f04cbcec2bad4b17415dd5d455964694f4d00a03e32929193fb0319971bc",
          "sha1": "d8949974b3a48db1a98b27a5e2565b4fe76e760d",
          "md5": "6834fe08cf5913efc05884c959350a08"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "awg-tunnel-1.0.20260624.aar",
          "url": "awg-tunnel-1.0.20260624.aar",
          "size": 6027587,
          "sha512": "8aeea53ecacbc7eeac915295da058402e51ffd3ac95e22735855ffa7d092aabfba9dbac73116ed30b0a4bba9702c98d931657067eb9ce3a8da9422c50d00b93a",
          "sha256": "4906f04cbcec2bad4b17415dd5d455964694f4d00a03e32929193fb0319971bc",
          "sha1": "d8949974b3a48db1a98b27a5e2565b4fe76e760d",
          "md5": "6834fe08cf5913efc05884c959350a08"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "awg-tunnel-1.0.20260624-sources.jar",
          "url": "awg-tunnel-1.0.20260624-sources.jar",
          "size": 47906,
          "sha512": "6e63a4481316e95f4a32fa989605f4c0de78bdbc4c129ea5d8f5ee2f94f8d64cd7a5c75949bb8dce96d9709eaaa5de60a0551d37fed7c5b94806b8ab7c77f75f",
          "sha256": "c834d5d286bea0b10933714d228c2cab27e23aabdf728f7e8d72bc238aa96028",
          "sha1": "4fad37fa8e27f6dc076b29948dadf2ffa74d9b6e",
          "md5": "24866a144b48b6d1feb1e846f172144e"
        }
      ]
    }
  ]
}
