# SPDX-License-Identifier: Apache-2.0
#
# Copyright © 2017-2023 WireGuard LLC. All Rights Reserved.

BUILDDIR ?= $(CURDIR)/build
DESTDIR ?= $(CURDIR)/out

NDK_GO_ARCH_MAP_x86 := 386
NDK_GO_ARCH_MAP_x86_64 := amd64
NDK_GO_ARCH_MAP_arm := arm
NDK_GO_ARCH_MAP_arm64 := arm64
NDK_GO_ARCH_MAP_mips := mipsx
NDK_GO_ARCH_MAP_mips64 := mips64x

comma := ,
CLANG_FLAGS := --target=$(TARGET) --sysroot=$(SYSROOT)
export CGO_CFLAGS := $(CLANG_FLAGS) $(subst -mthumb,-marm,$(CFLAGS))
export CGO_LDFLAGS := $(CLANG_FLAGS) $(patsubst -Wl$(comma)--build-id=%,-Wl$(comma)--build-id=none,$(LDFLAGS)) -Wl,-soname=libwg-go.so
export GOARCH := $(NDK_GO_ARCH_MAP_$(ANDROID_ARCH_NAME))
export GOOS := android
export CGO_ENABLED := 1
export GOENV := off
export GOTOOLCHAIN := local
export GOWORK := off

GO_VERSION := 1.25.0
HOST_GO_ARCH_x86_64 := amd64
HOST_GO_ARCH_amd64 := amd64
HOST_GO_ARCH_aarch64 := arm64
HOST_GO_ARCH_arm64 := arm64
GO_PLATFORM := $(shell uname -s | tr '[:upper:]' '[:lower:]')-$(HOST_GO_ARCH_$(shell uname -m))
GO_TARBALL := go$(GO_VERSION).$(GO_PLATFORM).tar.gz
GO_HASH_darwin-amd64 := 5bd60e823037062c2307c71e8111809865116714d6f6b410597cf5075dfd80ef
GO_HASH_darwin-arm64 := 544932844156d8172f7a28f77f2ac9c15a23046698b6243f633b0a0b00c0749c
GO_HASH_linux-amd64 := 2852af0cb20a13139b3448992e69b868e50ed0f8a1e5940ee1de9e19a123b613
GO_HASH_linux-arm64 := 05de75d6994a2783699815ee553bd5a9327d8b79991de36e38b66862782f54ae
GO_HASH := $(GO_HASH_$(GO_PLATFORM))
GO_SOURCES := $(wildcard *.go *.c *.h)

ifeq ($(GO_HASH),)
$(error Unsupported Go host platform: $(GO_PLATFORM))
endif

default: $(DESTDIR)/libwg-go.so

$(GRADLE_USER_HOME)/caches/golang/$(GO_TARBALL):
	mkdir -p "$(dir $@)"
	flock "$@.lock" -c ' \
	[ ! -f "$@" ] || echo "$(GO_HASH)  $@" | sha256sum -c || rm -f "$@"; \
	[ ! -f "$@" ] || exit 0; \
	curl --fail --location --show-error -o "$@.tmp" "https://go.dev/dl/$(GO_TARBALL)" && \
	echo "$(GO_HASH)  $@.tmp" | sha256sum -c && \
	mv "$@.tmp" "$@"'

$(BUILDDIR)/go-$(GO_VERSION)/.prepared: $(GRADLE_USER_HOME)/caches/golang/$(GO_TARBALL)
	mkdir -p "$(dir $@)"
	flock "$@.lock" -c ' \
	[ -f "$@" ] && exit 0; \
	tar -C "$(dir $@)" --strip-components=1 -xzf "$^" && \
	patch -p1 -f -N -r- -d "$(dir $@)" < goruntime-boottime-over-monotonic.diff && \
	touch "$@"'

$(DESTDIR)/libwg-go.so: export PATH := $(BUILDDIR)/go-$(GO_VERSION)/bin/:$(PATH)
$(DESTDIR)/libwg-go.so: $(BUILDDIR)/go-$(GO_VERSION)/.prepared Makefile go.mod go.sum $(GO_SOURCES) FORCE
	go build -mod=readonly -tags linux -ldflags="-X github.com/amnezia-vpn/amneziawg-go/ipc.socketDirectory=/data/data/$(ANDROID_PACKAGE_NAME)/cache/amneziawg -buildid=" -v -trimpath -buildvcs=false -o "$@" -buildmode c-shared

.PHONY: FORCE
FORCE:

.DELETE_ON_ERROR:
