{
  "formatVersion": "1.1",
  "component": {
    "group": "org.amnezia.awg",
    "module": "awg-tunnel",
    "version": "1.0.20240213",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "awg-tunnel-1.0.20240213.aar",
          "url": "awg-tunnel-1.0.20240213.aar",
          "size": 5238468,
          "sha512": "301dedd95c07a71478e12616ca16386175aeb90db7f24cfc2125a1978d2a16e63bc20834f3f86edc3a9f8269f17f813b9cb4090e634b1518160996209297eda8",
          "sha256": "f4974f993266ca1eddbf6b52b67dc4a57cbb25f11685ff685ce1a8bcf97d634f",
          "sha1": "9ce0322669c46fcb8cf8a85d950efd7bd2dd91b7",
          "md5": "2565bb6d3e35ac82628471d94f1ad10d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "awg-tunnel-1.0.20240213.aar",
          "url": "awg-tunnel-1.0.20240213.aar",
          "size": 5238468,
          "sha512": "301dedd95c07a71478e12616ca16386175aeb90db7f24cfc2125a1978d2a16e63bc20834f3f86edc3a9f8269f17f813b9cb4090e634b1518160996209297eda8",
          "sha256": "f4974f993266ca1eddbf6b52b67dc4a57cbb25f11685ff685ce1a8bcf97d634f",
          "sha1": "9ce0322669c46fcb8cf8a85d950efd7bd2dd91b7",
          "md5": "2565bb6d3e35ac82628471d94f1ad10d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "awg-tunnel-1.0.20240213-sources.jar",
          "url": "awg-tunnel-1.0.20240213-sources.jar",
          "size": 45079,
          "sha512": "5d8f953f70259a18d9b9491ff34c3c957387e87246874352663131549ab58be6b262fbf8d55589b69dbf6760f921e5479d3a97d6c8c347dcbe6e49c8f641cf4e",
          "sha256": "1e8fe93ee4a9bf46a619427919437431f1a508ae413cab0461ea2f97213faa09",
          "sha1": "0e7e4e9dec50ad805068627fe8513d3bc9f61987",
          "md5": "69dc8c5b99489728fb0dec2832fd8444"
        }
      ]
    }
  ]
}
